name: Feature request
description: Suggest an idea for this project 🦅🐆

body:
  - type: markdown
    attributes:
      value: Please make sure to browse the opened and closed issues to make sure that this idea has not previously been discussed.
