# Test file for automatic release after bumping version and deployment (full process)
# Currently leaves out the deployments steps because will not want to test that

name: full_deploy-and-release

on:
  push:
    branches:
      - main
    paths:
      - 'general_superstaq/_version.py' # either update for each repo or change to general '**/_version.py'
  workflow_dispatch: null # can also be triggered manually on Actions page

jobs: # groups together all jobs in this workflow
#   check_version_update: # defines a job named check_version_update
#     # not sure if we should add a needs: for the checks to run on main before this is triggered; 
#     # there have been times with unique timing of PRs merging where the version update checks would 
#     # fail merging into main but rare and maybe not significant?
#     # could possibly remove this job completely
#     runs-on: ubuntu-latest

#   deploy_aws:
#     needs: check_version_update # specifies dependency on previous job to run
#     runs-on: ubuntu-latest

  publish_release:
#     needs: check_version_update # needs to be updated to deploy_aws eventually
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3 # allows workflow to access repo
      - name: Set date for release title
        run: echo today=$(date +"%B %d, %Y") >> $GITHUB_ENV # format date and append to env
      - name: Set version number to most recent change
        run: echo version=$(cat general_superstaq/_version.py | grep -oP '[0-9\.]+') >> $GITHUB_ENV
      - name: Create and Publish release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.version }}
          name: v${{ env.version }} ${{ env.today }} Release
          generateReleaseNotes: true
          makeLatest: true
          
          
