name: "Automatic Deploy and release"

on:
  push:
    branches: 
      - main
        
jobs:
  run_checks:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'checks are running'
  deploy_and_release:
    needs: run_checks
    uses: ./.github/workflows/test2.yml
    
