name: "Manual Deploy and Release"

on:
  workflow_call: null # this will be called by the automatic deploy and release
  workflow_dispatch: null # can manually deploy and release (e.g., if checks fail or initial deploy fails)
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'deployed!'
        id: deploy
#   fake-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - run: exit 1
  release:
    runs-on: ubuntu-latest
    needs: deploy
    if: github.ref == 'refs/heads/main'
    steps:
      - run: echo 'release published'
