name: "Test Control Flow"

on:
  push:
    branches: 
      - main
  workflow_dispatch: 
    inputs:
      dispatch: # name of input
        required: true
        type: boolean
        default: true
        
jobs:
  run_checks:
    runs-on: ubuntu-latest
    if: ${{ !inputs.dispatch }}
    outputs:
      success_outcome: ${{ steps.success_check.outputs.result }}
    steps:
      - run: echo 'checks are running'
        id: run_checks
      - id: success_check
        if: success()
        run: echo "success" >> $GITHUB_OUTPUT
  deploy:
    runs-on: ubuntu-latest
    needs: run_checks
    if: (needs.run_checks.outputs.success_outcome == "success") || (inputs.dispatch)
    steps:
      - run: echo 'deployed!'
        id: deploy
  release:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - run: echo 'release published'
