name: "Test Control Flow"

on:
  push:
    branches: 
      - main
  workflow_dispatch: 
    inputs:
      dispatch: # name of input
        required: true
        type: boolean
        default: true
        
jobs:
  run_checks:
    runs-on: ubuntu-latest
    if: ${{ !inputs.dispatch }}
    steps:
      - run: echo 'checks are running'
        id: run_checks
      - if: success()
        run: echo pass=$"true" >> $GITHUB_ENV
      - run: echo '${{ env.pass }}'
  deploy:
    runs-on: ubuntu-latest
    needs: run_checks
    if: (inputs.dispatch)
    steps:
      - run: echo 'deployed!'
        id: deploy
  release:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - run: echo 'release published'
