name: "Automatic Deploy and release"

on:
  push:
    branches: 
      - main
        
jobs:
  run_checks:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'checks are running'
  deploy_and_release:
    needs: run_checks
#     if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/test2.yml
#     uses: ./.github/workflows/release_full_test.yml
    
