name: "Test Control Flow"

on:
  push:
    branches: 
      - main
        
jobs:
  run_checks:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'checks are running'
  deploy_and_release:
    uses: ./.github/workflows/test2.yml
#   deploy:
#     runs-on: ubuntu-latest
#     needs: run_checks
#     if: (needs.run_checks.outputs.success_outcome == 'success') || (inputs.dispatch)
#     steps:
#       - run: echo 'deployed!'
#         id: deploy
#   release:
#     runs-on: ubuntu-latest
#     needs: deploy
#     steps:
#       - run: echo 'release published'
