name: "Test Control Flow"

on:
  push:
    branches: 
      - main
  workflow_dispatch: 
    inputs:
      dispatch: # name of input
        required: true
        type: boolean
        default: true
        
jobs:
  hello-world:
    runs-on: ubuntu-latest
    if: ${{ inputs.dispatch != true }}
    steps:
      - run: echo 'hello world'
